image: ubuntu:17.10

stages:
  - test
  - deploy

before_script:
- bash ci/docker_install.sh

# test with OC10
test_oc10:
  stage: test
  only:
    refs:
      - master
  script:
    - mkdir -p /var/www/html ; cd /var/www/html
    - wget https://download.owncloud.org/community/owncloud-10.0.7.tar.bz2 ; tar xf owncloud-10.0.7.tar.bz2 ; rm owncloud-10.0.7.tar.bz2
    - chown -R www-data:www-data owncloud
    - cd owncloud/apps
    - git clone https://gitlab.com/eneiluj/phonetrack-oc phonetrack
    - sudo -u www-data php /var/www/html/owncloud/occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "password"
    - sudo -u www-data php /var/www/html/owncloud/occ app:enable phonetrack
    - sudo -u www-data php /var/www/html/owncloud/occ maintenance:mode --off
    - phpunit --configuration /var/www/html/owncloud/apps/phonetrack/phpunit.xml --coverage-text --color=never

# test with NC14 and produce coverage report
test_nc14:
  stage: test
  only:
    refs:
      - master
  artifacts:
    paths:
      - coverage
  coverage: '/^\s*Lines:\s*(\d+.\d+)\%/'
  script:
    - mkdir -p /var/www/html ; pushd /var/www/html
    - wget https://download.nextcloud.com/server/releases/nextcloud-14.0.0.zip ; unzip nextcloud-14.0.0.zip ; rm nextcloud-14.0.0.zip
    - chown -R www-data:www-data nextcloud
    - pushd nextcloud/apps
    - git clone https://gitlab.com/eneiluj/phonetrack-oc phonetrack
    - sudo -u www-data php /var/www/html/nextcloud/occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "password"
    - sudo -u www-data php /var/www/html/nextcloud/occ app:enable phonetrack
    - sudo -u www-data php /var/www/html/nextcloud/occ maintenance:mode --off
    - popd ; popd ; mkdir coverage
    - phpunit --configuration /var/www/html/nextcloud/apps/phonetrack/phpunit.xml --coverage-text --color=never --coverage-html coverage

pages:
  stage: deploy
  dependencies:
    - test_nc14
  before_script:
    - echo 'nothing to install for pages jobs'
  only:
    refs:
      - master
  artifacts:
    paths:
      - public
  script:
    - sleep 5
    - mkdir public
    - mv coverage public/
